/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package poly.barber.view.Dialog;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import poly.barber.entity.ServiceCategory;
import poly.barber.repository.ServiceCategoryRepository;

/**
 *
 * @author DELL
 */
public class LoaiJDialog extends javax.swing.JDialog {

    private ServiceCategoryRepository scr = new ServiceCategoryRepository();
    private DefaultTableModel dtm = new DefaultTableModel();

    private List<ServiceCategory> listGlobal = new java.util.ArrayList<>();

    /**
     * Creates new form Loai1JDialog
     */
    public LoaiJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        dtm = (DefaultTableModel) tblServiceCategory.getModel();
        showTable(scr.getAll());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        btnXoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblServiceCategory = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Mã");

        txtMa.setEditable(false);
        txtMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        jLabel2.setText("Tên");

        txtTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenActionPerformed(evt);
            }
        });

        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        tblServiceCategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã", "Tên"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblServiceCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblServiceCategoryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblServiceCategory);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMa, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtTen))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSua)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem)
                    .addComponent(btnSua))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaActionPerformed

    private void txtTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        txtMa.setText("");
        if (checkValidate()) {
            try {
                ServiceCategory sc = getForm();
                scr.add(sc);

                javax.swing.JOptionPane.showMessageDialog(this, "Thêm thành công!");
                showTable(scr.getAll());
                clearForm();
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Lỗi thêm!");
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if (txtMa.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn loại để sửa!");
            return;
        }

        if (checkValidate()) {
            try {
                ServiceCategory sc = getForm();
                scr.update(sc);

                javax.swing.JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
                showTable(scr.getAll());
                clearForm();
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Lỗi cập nhật!");
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if (txtMa.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn loại để xoá!");
            return;
        }

        int confirm = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc muốn xoá không?",
                "Xác nhận",
                javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            try {
                int id = Integer.parseInt(txtMa.getText().trim());
                scr.delete(id);

                javax.swing.JOptionPane.showMessageDialog(this, "Xoá thành công!");
                showTable(scr.getAll());
                clearForm();
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Không thể xoá! Có thể đang được sử dụng.");
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblServiceCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblServiceCategoryMouseClicked
        int index = tblServiceCategory.getSelectedRow();
        if (index >= 0) {
            detail(listGlobal, index); // Sử dụng list đang hiển thị thay vì sr.getAll()
        }// TODO add your handling code here:
    }//GEN-LAST:event_tblServiceCategoryMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoaiJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoaiJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoaiJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoaiJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoaiJDialog dialog = new LoaiJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblServiceCategory;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables

    private void showTable(List<ServiceCategory> all) {
        dtm.setRowCount(0);
        this.listGlobal = all;

        List<ServiceCategory> listCategories = scr.getAll();

        for (ServiceCategory s : listCategories) {
            dtm.addRow(new Object[]{
                s.getServiceCategoryID(),
                s.getServiceCategoryName()
            });
        }
    }

    private void detail(List<ServiceCategory> all, int index) {
        ServiceCategory s = all.get(index);
        txtMa.setText(s.getServiceCategoryID() + "");
        txtTen.setText(s.getServiceCategoryName());
    }

    private ServiceCategory getForm() {
        ServiceCategory s = new ServiceCategory();
        String ma = txtMa.getText().trim();
        if (!ma.isEmpty()) {
            s.setServiceCategoryID(Integer.parseInt(ma));
        }
        s.setServiceCategoryName(txtTen.getText().trim());
        return s;
    }

    private boolean checkValidate() {
        String ten = txtTen.getText().trim();
        String maStr = txtMa.getText().trim();

        if (ten.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Tên dịch vụ không được để trống!");
            txtTen.requestFocus();
            return false;
        }

        ServiceCategory sCheck = scr.getByName(ten);

        if (sCheck != null) {
            if (maStr.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Tên dịch vụ đã tồn tại!");
                return false;
            } else {
                int idForm = Integer.parseInt(maStr);

                if (sCheck.getServiceCategoryID() != idForm) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Tên dịch vụ đã tồn tại ở bản ghi khác!");
                    return false;
                }
            }
        }
        return true;
    }

    private void clearForm() {
        txtMa.setText("");
        txtTen.setText("");
    }
}
