/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package poly.barber.view.Dialog;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import poly.barber.entity.Service;
import poly.barber.entity.ServiceCategory;
import poly.barber.repository.ServiceCategoryRepository;
import poly.barber.repository.ServiceRepository;

/**
 *
 * @author DELL
 */
public class ServiceJDialog extends javax.swing.JDialog {

    private ServiceCategoryRepository scr = new ServiceCategoryRepository();
    private ServiceRepository sr = new ServiceRepository();
    private DefaultTableModel dtm = new DefaultTableModel();
    private DefaultComboBoxModel dcbm = new DefaultComboBoxModel();

    private List<Service> listGlobal = new java.util.ArrayList<>();

    /**
     * Creates new form ServiceJDialog
     */
    public ServiceJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);

        dtm = (DefaultTableModel) tblService.getModel();
        dcbm = (DefaultComboBoxModel) cboLoai.getModel();
        showTable(sr.getAll());
        showComBoBox(scr.getAll());
        reloadCboLocLoai();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        txtTime = new javax.swing.JTextField();
        cboLoai = new javax.swing.JComboBox<>();
        btnTableLoai = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        cboLocLoai = new javax.swing.JComboBox<>();
        btnLoc = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblService = new javax.swing.JTable();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setToolTipText("Thông tin dịch vụ");

        jLabel1.setText("THÔNG TIN DỊCH VỤ");

        jLabel2.setText("Mã");

        jLabel3.setText("Tên");

        jLabel4.setText("Giá");

        jLabel5.setText("Thời gian");

        jLabel6.setText("Loại");

        txtMa.setEditable(false);

        txtGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaActionPerformed(evt);
            }
        });

        cboLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboLoai.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboLoaiItemStateChanged(evt);
            }
        });
        cboLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLoaiActionPerformed(evt);
            }
        });

        btnTableLoai.setText("+");
        btnTableLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTableLoaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(cboLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTableLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtMa)
                    .addComponent(txtTen)
                    .addComponent(txtGia)
                    .addComponent(txtTime))
                .addGap(72, 72, 72))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTableLoai)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        cboLocLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboLocLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLocLoaiActionPerformed(evt);
            }
        });

        btnLoc.setText("Lọc");
        btnLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocActionPerformed(evt);
            }
        });

        jLabel7.setText("Loại");

        tblService.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã", "Tên", "Giá", "Thời gian", "Loại"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblService.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblServiceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblService);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboLocLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLoc))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(jLabel7)
                    .addComponent(btnLoc)
                    .addComponent(cboLocLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Danh sách dịch vụ", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblServiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblServiceMouseClicked
        int index = tblService.getSelectedRow();
        if (index >= 0) {
            detailSp(listGlobal, index); // Sử dụng list đang hiển thị thay vì sr.getAll()
        }
    }//GEN-LAST:event_tblServiceMouseClicked

    private void cboLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLoaiActionPerformed

    }//GEN-LAST:event_cboLoaiActionPerformed

    private void cboLoaiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboLoaiItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cboLoaiItemStateChanged

    private void txtGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        txtMa.setText("");
        if (checkValidate()) {
            try {
                Service s = getForm();
                sr.add(s);
                javax.swing.JOptionPane.showMessageDialog(this, "Thêm thành công!");
                showTable(sr.getAll());
                clearForm();
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Lỗi thêm mới!");
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if (checkValidate()) {
            try {
                Service s = getForm();
                sr.update(s);
                javax.swing.JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
                showTable(sr.getAll());
                clearForm();
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Lỗi cập nhật: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocActionPerformed
        Object selectedItem = cboLocLoai.getSelectedItem();

        if (selectedItem == null) {
            return;
        }

        // Nếu người dùng chọn "Tất cả" (là String)
        if (selectedItem instanceof String && selectedItem.equals("Tất cả")) {
            showTable(sr.getAll()); // Hiển thị toàn bộ danh sách
        } // Nếu người dùng chọn một loại cụ thể (là ServiceCategory)
        else if (selectedItem instanceof ServiceCategory) {
            ServiceCategory sc = (ServiceCategory) selectedItem;
            List<Service> filteredList = sr.getByType(sc.getServiceCategoryID());
            showTable(filteredList);

            if (filteredList.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Không có dịch vụ nào thuộc loại này.");
            }
        }
    }//GEN-LAST:event_btnLocActionPerformed

    private void btnTableLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTableLoaiActionPerformed
        LoaiJDialog dialog = new LoaiJDialog((java.awt.Frame) this.getOwner(), true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);

        reloadCboLocLoai();
        showComBoBox(scr.getAll());
    }//GEN-LAST:event_btnTableLoaiActionPerformed

    private void cboLocLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLocLoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboLocLoaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServiceJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServiceJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServiceJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServiceJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ServiceJDialog dialog = new ServiceJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoc;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnTableLoai;
    private javax.swing.JButton btnThem;
    private javax.swing.JComboBox<String> cboLoai;
    private javax.swing.JComboBox<String> cboLocLoai;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblService;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables

    private void showTable(List<Service> all) {
        java.text.DecimalFormat df = new java.text.DecimalFormat("#,###");
        dtm.setRowCount(0);
        this.listGlobal = all;

        List<ServiceCategory> listCategories = scr.getAll();

        for (Service s : all) {
            String formattedPrice = (s.getPrice() != null) ? df.format(s.getPrice()) + " VNĐ" : "0 VNĐ";

            String categoryName = "Không xác định";
            for (ServiceCategory sc : listCategories) {
                if (sc.getServiceCategoryID() == s.getServiceCategoryID()) {
                    categoryName = sc.getServiceCategoryName();
                    break;
                }
            }

            dtm.addRow(new Object[]{
                s.getServiceID(),
                s.getServiceName(),
                formattedPrice,
                s.getDuration() + " phút",
                categoryName
            });
        }
    }

    private void showComBoBox(List<ServiceCategory> all) {
        dcbm.removeAllElements();
        for (ServiceCategory sc : all) {
            dcbm.addElement(sc);
        }
    }

    private void detailSp(List<Service> all, int index) {
        Service s = all.get(index);
        txtMa.setText(s.getServiceID() + "");
        txtTen.setText(s.getServiceName());

        txtGia.setText(s.getPrice().toPlainString());
        txtTime.setText(s.getDuration() + "");

        for (int i = 0; i < cboLoai.getItemCount(); i++) {
            Object item = cboLoai.getItemAt(i);

            if (item instanceof ServiceCategory) {
                ServiceCategory sc = (ServiceCategory) item;
                if (sc.getServiceCategoryID() == s.getServiceCategoryID()) {
                    cboLoai.setSelectedIndex(i);
                    break;
                }
            }
        }
    }

    private Service getForm() {
        Service s = new Service();
        String ma = txtMa.getText().trim();
        if (!ma.isEmpty()) {
            s.setServiceID(Integer.parseInt(ma));
        }

        s.setServiceName(txtTen.getText().trim());

        String giaStr = txtGia.getText().trim();
        s.setPrice(new java.math.BigDecimal(giaStr.isEmpty() ? "0" : giaStr));

        String timeStr = txtTime.getText().trim();
        s.setDuration(timeStr.isEmpty() ? 0 : Integer.parseInt(timeStr));

        ServiceCategory selectedCat = (ServiceCategory) cboLoai.getSelectedItem();
        if (selectedCat != null) {
            s.setServiceCategoryID(selectedCat.getServiceCategoryID());
        }
        return s;
    }

    private boolean checkValidate() {
        String ten = txtTen.getText().trim();
        String giaStr = txtGia.getText().trim();
        String thoiGianStr = txtTime.getText().trim();
        String maStr = txtMa.getText().trim();

        // 1. Kiểm tra trống
        if (ten.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Tên dịch vụ không được để trống!");
            txtTen.requestFocus();
            return false;
        }

        if (giaStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Giá không được để trống!");
            txtGia.requestFocus();
            return false;
        }

        // 2. Kiểm tra định dạng số cho Giá
        try {
            java.math.BigDecimal gia = new java.math.BigDecimal(giaStr);
            if (gia.compareTo(java.math.BigDecimal.ZERO) < 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Giá không được là số âm!");
                return false;
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Giá phải là số hợp lệ!");
            return false;
        }

        // 3. Kiểm tra định dạng số cho Thời gian
        try {
            int time = Integer.parseInt(thoiGianStr);
            if (time <= 0) {
                throw new Exception();
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Thời gian phải là số nguyên dương!");
            return false;
        }

        // 4. Kiểm tra trùng tên (Logic quan trọng)
        Service sCheckTen = sr.getByName(ten);

        if (sCheckTen != null) {
            // Nếu tìm thấy tên này trong DB, ta phải xác định đang "Thêm" hay "Sửa"
            // Cách tốt nhất: Nếu bạn đang bấm nút THÊM, thì tuyệt đối không được trùng

            // Giả sử ta kiểm tra nếu txtMa đang hiển thị ID của chính thằng trùng đó
            String maForm = txtMa.getText().trim();

            // Nếu txtMa trống (thêm mới chuẩn) HOẶC bạn đang bấm nút Thêm nhưng Form lại có ID
            // Cách an toàn: Trong nút THÊM, hãy coi như mọi trường hợp tìm thấy sCheckTen đều là lỗi
            if (maForm.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Tên dịch vụ đã tồn tại!");
                return false;
            } else {
                // Nếu có ID trên Form, chỉ cho phép đi tiếp nếu ID đó TRÙNG với ID của tên vừa tìm thấy (nghĩa là không sửa tên)
                int idTrenForm = Integer.parseInt(maForm);
                if (sCheckTen.getServiceID() != idTrenForm) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Tên này đã tồn tại ở một mã dịch vụ khác!");
                    return false;
                }
            }
        }
        return true;
    }

    private void clearForm() {
        txtMa.setText("");
        txtTen.setText("");
        txtGia.setText("");
        txtTime.setText("");
        if (cboLoai.getItemCount() > 0) {
            cboLoai.setSelectedIndex(0);
        }
        tblService.clearSelection();
    }

    private void reloadCboLocLoai() {
        List<ServiceCategory> list = scr.getAll();
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboLocLoai.getModel();

        model.removeAllElements();
        model.addElement("Tất cả");

        for (ServiceCategory sc : list) {
            model.addElement(sc);
        }

        cboLocLoai.setSelectedIndex(0);
    }
}
